# Generated by Django 5.1.3 on 2024-11-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
