# Generated by Django 5.1.3 on 2024-11-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reservation_guest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
